# Status Line: Model name + Context usage with progress bar
# Generated by /statusline

$raw = [Console]::In.ReadToEnd()
if ([string]::IsNullOrWhiteSpace($raw)) { exit 0 }

try {
  $inputJson = $raw | ConvertFrom-Json
} catch {
  exit 0
}

$model = $inputJson.model.display_name
$used = $inputJson.context_window.used_percentage

if ($null -eq $used) {
  $pct = 0
} else {
  $pct = [math]::Round([double]$used)
}

# Build 20-char progress bar
$barWidth = 20
$filled = [math]::Floor($pct * $barWidth / 100)
$empty = $barWidth - $filled

# ANSI color based on usage
if ($pct -lt 50) {
  $color = [char]27 + "[32m"   # green
} elseif ($pct -lt 80) {
  $color = [char]27 + "[33m"   # yellow
} else {
  $color = [char]27 + "[31m"   # red
}
$reset = [char]27 + "[0m"

$bar = ("#" * $filled) + ("-" * $empty)

Write-Output ("{0} [{1}{2}{3}] {4}%" -f $model, $color, $bar, $reset, $pct)
