#!/usr/bin/env bash
# Status Line: Model name + Context usage with progress bar
# Generated by /statusline
set -euo pipefail

input=$(cat)

# Extract model display name
model=$(echo "$input" | jq -r '.model.display_name // "Unknown"')

# Extract context used percentage (0-100)
pct=$(echo "$input" | jq -r '.context_window.used_percentage // 0')
pct_int=$(printf "%.0f" "$pct")

# Build a 20-character progress bar
bar_width=20
filled=$(( pct_int * bar_width / 100 ))
empty=$(( bar_width - filled ))

bar=""
for (( i=0; i<filled; i++ )); do bar="${bar}#"; done
for (( i=0; i<empty; i++ )); do bar="${bar}-"; done

# Choose color based on usage level
# <50 green, 50-80 yellow, >80 red
if [ "$pct_int" -lt 50 ]; then
  color="\033[32m"
elif [ "$pct_int" -lt 80 ]; then
  color="\033[33m"
else
  color="\033[31m"
fi
reset="\033[0m"

printf "${model} [${color}${bar}${reset}] %d%%" "$pct_int"
