/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import React from 'react';
import { Text } from 'ink';
import { SettingScope } from '../../config/settings.js';
import type {
  CommandContext,
  SlashCommandActionReturn,
} from '../commands/types.js';

function buildWindowsTemplate(userPrompt: string): string {
  return `# Generated by /statusline
# Request: ${userPrompt || 'default'}
$raw = [Console]::In.ReadToEnd()
if ([string]::IsNullOrWhiteSpace($raw)) { exit 0 }

try {
  $inputJson = $raw | ConvertFrom-Json
} catch {
  exit 0
}

$cwd = $inputJson.workspace.current_dir
$folder = Split-Path -Leaf $cwd
$model = $inputJson.model.display_name
$used = $inputJson.context_window.used_percentage
$context = if ($null -ne $used) { '{0:N0}%' -f [double]$used } else { 'n/a' }
$branch = ''

try {
  $branch = (git -C $cwd branch --show-current 2>$null).Trim()
} catch {
  $branch = ''
}

if ($branch) {
  Write-Output "[$branch] $folder | $model | ctx $context"
} else {
  Write-Output "$folder | $model | ctx $context"
}
`;
}

function buildPosixTemplate(userPrompt: string): string {
  return `#!/usr/bin/env bash
# Generated by /statusline
# Request: ${userPrompt || 'default'}
set -euo pipefail

node - <<'NODE'
const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');

const raw = fs.readFileSync(0, 'utf8');
if (!raw.trim()) {
  process.exit(0);
}

let input;
try {
  input = JSON.parse(raw);
} catch {
  process.exit(0);
}

const cwd = input.workspace?.current_dir || input.cwd || process.cwd();
const folder = path.basename(cwd);
const model = input.model?.display_name || input.model?.id || 'unknown';
const used = input.context_window?.used_percentage;
const context = typeof used === 'number' ? Math.round(used) + '%' : 'n/a';
let branch = '';

try {
  branch = execFileSync('git', ['-C', cwd, 'branch', '--show-current'], {
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'ignore'],
  }).trim();
} catch {}

const prefix = branch ? '[' + branch + '] ' : '';
process.stdout.write(prefix + folder + ' | ' + model + ' | ctx ' + context);
NODE
`;
}

function getScriptInfo() {
  const qwenDir = path.join(os.homedir(), '.qwen');
  if (os.platform() === 'win32') {
    const scriptPath = path.join(qwenDir, 'statusline.ps1');
    return {
      qwenDir,
      scriptPath,
      command: `powershell -NoProfile -File "${scriptPath}"`,
      template: buildWindowsTemplate,
    };
  }

  const scriptPath = path.join(qwenDir, 'statusline.sh');
  return {
    qwenDir,
    scriptPath,
    command: `"${scriptPath}"`,
    template: buildPosixTemplate,
  };
}

function getExistingContent(scriptPath: string): string | undefined {
  if (!fs.existsSync(scriptPath)) {
    return undefined;
  }

  try {
    return fs.readFileSync(scriptPath, 'utf8');
  } catch {
    return undefined;
  }
}

export async function runStatusLineSetup(
  context: CommandContext,
  prompt: string,
): Promise<SlashCommandActionReturn> {
  const { qwenDir, scriptPath, command, template } = getScriptInfo();
  const existingContent = getExistingContent(scriptPath);

  if (existingContent && existingContent.trim().length > 0) {
    if (!context.overwriteConfirmed) {
      return {
        type: 'confirm_action',
        prompt: React.createElement(
          Text,
          null,
          'A statusline script already exists. Do you want to overwrite it?',
        ),
        originalInvocation: {
          raw: context.invocation?.raw || '/statusline',
        },
      };
    }
  }

  fs.mkdirSync(qwenDir, { recursive: true });
  fs.writeFileSync(scriptPath, template(prompt.trim()), 'utf8');

  if (os.platform() !== 'win32') {
    fs.chmodSync(scriptPath, 0o755);
  }

  context.services.settings.setValue(SettingScope.User, 'ui.statusLine', {
    type: 'command',
    command,
    padding: 2,
  });
  context.ui.reloadCommands();

  const notes: string[] = [];
  if (context.services.config?.getDisableAllHooks()) {
    notes.push(
      'Status line is configured, but it is currently disabled because disableAllHooks is enabled.',
    );
  } else if (context.services.config && !context.services.config.isTrustedFolder()) {
    notes.push(
      'Status line is configured, but it will not run until this workspace is trusted.',
    );
  }

  return {
    type: 'message',
    messageType: 'info',
    content: [`Status line configured: ${scriptPath}`, ...notes].join('\n'),
  };
}
